/* This file is auto-generated by typed-bridge. Do not edit. */
type TypedBridge = {
    'user.fetch': (args: {
        id: number;
    }) => Promise<{
        id: number;
        name: string;
        email: string;
        createdAt: Date;
    }>;
    'user.create': (args: {
        name: string;
        email: string;
    }) => Promise<{
        id: number;
        name: string;
        email: string;
        createdAt: Date;
    }>;
    'user.update': (args: {
        id: number;
        name?: string | undefined;
        email?: string | undefined;
    }) => Promise<{
        id: number;
        name: string;
        email: string;
        createdAt: Date;
    }>;
    'user.remove': (args: {
        id: number;
    }) => Promise<{
        success: boolean;
    }>;
    'user.fetchAll': (args?: undefined) => Promise<{
        id: number;
        name: string;
        email: string;
        createdAt: Date;
    }[]>;
    'product.fetch': (args: {
        id: number;
    }) => Promise<{
        id: number;
        name: string;
        price: number;
        createdAt: Date;
    }>;
    'product.create': (args: {
        name: string;
        price: number;
    }) => Promise<{
        id: number;
        name: string;
        price: number;
        createdAt: Date;
    }>;
    'product.list': (args?: undefined) => Promise<{
        id: number;
        name: string;
        price: number;
        createdAt: Date;
    }[]>;
    'order.create': (args: {
        customerId: number;
        items: {
            productId: number;
            quantity: number;
            price: number;
            discount: number | null;
            notes?: string | undefined;
        }[];
        shippingAddress: {
            street: string;
            city: string;
            state: string;
            zip: string;
            country: string;
        };
        billingAddress: {
            street: string;
            city: string;
            state: string;
            zip: string;
            country: string;
        } | null;
        isGift: boolean;
        giftMessage: string | null;
        couponCode?: string | null | undefined;
        scheduledDate?: Date | undefined;
    }) => Promise<{
        id: number;
        status: "pending" | "confirmed" | "shipped" | "delivered" | "cancelled";
        total: number;
        items: {
            productId: number;
            quantity: number;
            price: number;
            discount: number | null;
            notes?: string | undefined;
        }[];
        createdAt: Date;
    }>;
    'order.fetch': (args: {
        id: number;
    }) => Promise<{
        id: number;
        customerId: number;
        status: "pending" | "confirmed" | "shipped" | "delivered" | "cancelled";
        total: number;
        items: {
            productId: number;
            quantity: number;
            price: number;
            discount: number | null;
            notes?: string | undefined;
        }[];
        shippingAddress: {
            street: string;
            city: string;
            state: string;
            zip: string;
            country: string;
        };
        billingAddress: {
            street: string;
            city: string;
            state: string;
            zip: string;
            country: string;
        } | null;
        isGift: boolean;
        giftMessage: string | null;
        createdAt: Date;
        updatedAt: Date | null;
    }>;
    'order.update': (args: {
        id: number;
        status?: "pending" | "confirmed" | "shipped" | "delivered" | "cancelled" | undefined;
        shippingAddress?: {
            street: string;
            city: string;
            state: string;
            zip: string;
            country: string;
        } | undefined;
        giftMessage?: string | null | undefined;
    }) => Promise<{
        id: number;
        status: "pending" | "confirmed" | "shipped" | "delivered" | "cancelled";
        updatedAt: Date;
    }>;
    'order.list': (args?: undefined) => Promise<{
        id: number;
        customerId: number;
        status: "pending" | "confirmed" | "shipped" | "delivered" | "cancelled";
        total: number;
        items: {
            productId: number;
            quantity: number;
            price: number;
            discount: number | null;
            notes?: string | undefined;
        }[];
        shippingAddress: {
            street: string;
            city: string;
            state: string;
            zip: string;
            country: string;
        };
        billingAddress: {
            street: string;
            city: string;
            state: string;
            zip: string;
            country: string;
        } | null;
        isGift: boolean;
        giftMessage: string | null;
        createdAt: Date;
        updatedAt: Date | null;
    }[]>;
    'order.resolve': (args: {
        id: number;
    }) => Promise<{
        status: "found";
        order: {
            id: number;
            customerName: string;
            orderStatus: "pending" | "confirmed" | "shipped" | "delivered" | "cancelled";
            total: number;
        };
    } | {
        status: "not_found";
    }>;
    'order.statusFilter': (args: {
        status: "pending" | "confirmed" | "shipped" | "delivered" | "cancelled";
    }) => Promise<{
        orders: {
            id: number;
            status: "pending" | "confirmed" | "shipped" | "delivered" | "cancelled";
            total: number;
        }[];
    }>;
    'order.tag': (args: {
        orderId: number;
        tag: string | number;
    }) => Promise<{
        orderId: number;
        tag: string | number;
        appliedAt: Date;
    }>;
    'order.primitives': (args: {
        key: string;
    }) => Promise<{
        str: string;
        num: number;
        bool: boolean;
        date: Date;
        nul: null;
        undef: undefined;
        unk: unknown;
        whatever: any;
        nullStr: string | null;
        defStr: string;
        tags: string[];
        scores: number[] | null;
        nested: {
            a: number;
            c: {
                d: boolean;
                e: string[] | null;
            };
            b?: string | undefined;
        };
        optStr?: string | undefined;
        optNullStr?: string | null | undefined;
        nullOptStr?: string | null | undefined;
        optDates?: Date[] | undefined;
    }>;
};

type TypedBridgeConfig = {
    host: string
    headers: Record<string, string>
    onResponse: (response: Response) => void
}

export const typedBridgeConfig: TypedBridgeConfig = {
    host: '',
    headers: { 'Content-Type': 'application/json' },
    onResponse: () => {}
}

export const typedBridge = new Proxy(
    {},
    {
        get(_, methodName: string) {
            return async (args: unknown) => {
                const response = await fetch(
                    typedBridgeConfig.host + (typedBridgeConfig.host.endsWith('/') ? '' : '/') + methodName,
                    {
                        method: 'POST',
                        headers: typedBridgeConfig.headers,
                        body: JSON.stringify(args)
                    }
                )

                typedBridgeConfig.onResponse(response)

                if (!response.ok) {
                    const errorText = await response.text()
                    console.error('REQ_FAILED', response.url, errorText)
                    throw new Error(errorText)
                }

                return response.json().catch(error => {
                    console.error('RES_NOT_JSON', response.url, error)
                    throw new Error(error.message)
                })
            }
        }
    }
) as TypedBridge

export default typedBridge
